### ISSUE TITLE
Open graph in a dedicated page

### ISSUE THREAD

**Issue by fedemengo** [kctekn/obsidian-TagsRoutes#1]
First of all, awesome work! It's really great.

It doesn't seem to be possible to open the graph in a dedicated page, it's always opened as a split view. Would it be possible to open it in a new page for better exploration?

**Comment by kctekn** [comment]
Thank you for your comment! You can drag the page tab to your current view so that it will be on the same page. Alternatively, you can drag it to the side view on the right, where it will dock for easier navigation. I’m not exactly sure what you mean by "new page." Do you mean a pop-up window? If so, it might cause users to switch between windows frequently when editing files.
