### ISSUE TITLE
how to match backgroung color to my current theme

### ISSUE THREAD

**Issue by JE-Amouel** [kctekn/obsidian-TagsRoutes#11]
HI,
thanks for your great plugins, pretty usefull :+1: 

i wonder how to set the background color of the scene?
is it possible to add an automode background color matching? along whith a manual one?

**Comment by kctekn** [comment]
Thank you for your feedback, and I'm glad to hear you're finding the plugins useful! 😊

At the moment, setting the background color to something other than the default dark color isn't supported. This limitation is due to the potential adverse effects on the scene's appearance, as other colors may make the scene too light, obscuring important details. Additionally, it currently seems outside the scope of the framework we're using.

While I understand the desire for more customization, this feature isn't something we're able to explore right now. However, I appreciate your suggestion and will certainly keep it in mind for future updates if the framework evolves to support it.

If you have any more questions or need further assistance, please don't hesitate to reach out!

**Comment by kctekn** [comment]
This feature has been supported since the version 1.1.0.
